server:
  port: 8880

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/

spring:
  application:
    name: cloud-eureka-server
