server:
  port: 8883
spring:
  application:
    name: cloud-eureka-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/
feign:
  hystrix:
    enabled: true

